require_relative 'ZagorskiADT/AbstractDataTypes/ADT.rb'
require_relative 'ZagorskiADT/AbstractDataTypes/Stack.rb'
require_relative 'ZagorskiADT/AbstractDataTypes/Queue.rb'
require_relative 'ZagorskiADT/AbstractDataTypes/StackQueue.rb'
require_relative 'ZagorskiADT/AbstractDataTypes/MinMaxStack.rb'
require_relative 'ZagorskiADT/AbstractDataTypes/MinMaxStackQueue.rb'
